### ISSUE TITLE
Does it only work over laravel 5.2 ?

### ISSUE THREAD

**Issue by perrywang** [DigitLab/adaptive-view#2]
I quickly check it with my laravel 5,1,x project  and it doesn't work at all. It always show my main view and ignore same name with mobile.blade.php postfix view.

**Comment by nrwiersma** [comment]
Hi,

I see no reason it shouldn't work on Laravel 5.1.x, although I have only tested it on 5.2.x. How are you testing the mobile views?

**Comment by nrwiersma** [comment]
Hi,

Just gave it a test (v1.1.0) in Laravel 5.1.x, and it seems to work fine. What version of adaptive-view are you using, what are your view names? Did you setup Agent?

**Comment by perrywang** [comment]
I just composer require agent and adaptive view and add two providers in congfig and one facade for Agent. And I have one view home.blade.php and I create another home.mobile.blade.php

**Comment by nrwiersma** [comment]
Any chance you can put your project on github temparaly? Then I can check it out and see what is going on. If not, I can create a test project for you, that is working for me.

**Comment by nrwiersma** [comment]
It occurred to me that the problem might be that Agent is not picking your device up as mobile. Check out Agent::isMobile() to see if it says thinks your test device is mobile.

**Comment by perrywang** [comment]
I find the reason it is conflicting with package frozennode/administrator that break up this view finder. You can try it. Once I removed Frozennode\Administrator\AdministratorServiceProvider::class everything is working. For this is widely used administrator package could you please kindly compatible running ? Actually I doubt it is conflicting with view composer function after I checked administrator's code.

**Comment by nrwiersma** [comment]
Hi,

Ok, I worked it out. I seems your other package is registering view composers, and you have added adaptive-view after frozennode/administrator in the providers array. Just put adaptive view before frozennode/administrator in your providers array, that seems to sort it out. I will update the docs to reflect this.

**Comment by perrywang** [comment]
Nice！

**Comment by nrwiersma** [comment]
Is this solved? Can I close the issue?
